import { defineConfig } from 'vite';
import path from 'path';

export default defineConfig({
  build: {
    lib: {
      entry: path.resolve(__dirname, 'src/tag.ts'),
      name: 'InsightAnalytics',
      fileName: () => 'insight-tag.js',
      formats: ['iife'],
    },
    outDir: 'dist',
    emptyOutDir: false, // Retain files generated by tsc (e.g. type definitions)
  }
});
