/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashUsersRouteImport } from './routes/_dash.users'
import { Route as DashSitemapRouteImport } from './routes/_dash.sitemap'
import { Route as DashSettingsRouteImport } from './routes/_dash.settings'
import { Route as DashSessionsRouteImport } from './routes/_dash.sessions'
import { Route as DashReportsRouteImport } from './routes/_dash.reports'
import { Route as DashProjectsRouteImport } from './routes/_dash.projects'
import { Route as DashOverviewRouteImport } from './routes/_dash.overview'
import { Route as DashMediaRouteImport } from './routes/_dash.media'
import { Route as DashFunnelsRouteImport } from './routes/_dash.funnels'
import { Route as DashEventsRouteImport } from './routes/_dash.events'
import { Route as DashDocumentationRouteImport } from './routes/_dash.documentation'
import { Route as DashApiKeysRouteImport } from './routes/_dash.api-keys'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashUsersRoute = DashUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashRoute,
} as any)
const DashSitemapRoute = DashSitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => DashRoute,
} as any)
const DashSettingsRoute = DashSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashRoute,
} as any)
const DashSessionsRoute = DashSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => DashRoute,
} as any)
const DashReportsRoute = DashReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashRoute,
} as any)
const DashProjectsRoute = DashProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashRoute,
} as any)
const DashOverviewRoute = DashOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashRoute,
} as any)
const DashMediaRoute = DashMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => DashRoute,
} as any)
const DashFunnelsRoute = DashFunnelsRouteImport.update({
  id: '/funnels',
  path: '/funnels',
  getParentRoute: () => DashRoute,
} as any)
const DashEventsRoute = DashEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashRoute,
} as any)
const DashDocumentationRoute = DashDocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => DashRoute,
} as any)
const DashApiKeysRoute = DashApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api-keys': typeof DashApiKeysRoute
  '/documentation': typeof DashDocumentationRoute
  '/events': typeof DashEventsRoute
  '/funnels': typeof DashFunnelsRoute
  '/media': typeof DashMediaRoute
  '/overview': typeof DashOverviewRoute
  '/projects': typeof DashProjectsRoute
  '/reports': typeof DashReportsRoute
  '/sessions': typeof DashSessionsRoute
  '/settings': typeof DashSettingsRoute
  '/sitemap': typeof DashSitemapRoute
  '/users': typeof DashUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api-keys': typeof DashApiKeysRoute
  '/documentation': typeof DashDocumentationRoute
  '/events': typeof DashEventsRoute
  '/funnels': typeof DashFunnelsRoute
  '/media': typeof DashMediaRoute
  '/overview': typeof DashOverviewRoute
  '/projects': typeof DashProjectsRoute
  '/reports': typeof DashReportsRoute
  '/sessions': typeof DashSessionsRoute
  '/settings': typeof DashSettingsRoute
  '/sitemap': typeof DashSitemapRoute
  '/users': typeof DashUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dash': typeof DashRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_dash/api-keys': typeof DashApiKeysRoute
  '/_dash/documentation': typeof DashDocumentationRoute
  '/_dash/events': typeof DashEventsRoute
  '/_dash/funnels': typeof DashFunnelsRoute
  '/_dash/media': typeof DashMediaRoute
  '/_dash/overview': typeof DashOverviewRoute
  '/_dash/projects': typeof DashProjectsRoute
  '/_dash/reports': typeof DashReportsRoute
  '/_dash/sessions': typeof DashSessionsRoute
  '/_dash/settings': typeof DashSettingsRoute
  '/_dash/sitemap': typeof DashSitemapRoute
  '/_dash/users': typeof DashUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/api-keys'
    | '/documentation'
    | '/events'
    | '/funnels'
    | '/media'
    | '/overview'
    | '/projects'
    | '/reports'
    | '/sessions'
    | '/settings'
    | '/sitemap'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/api-keys'
    | '/documentation'
    | '/events'
    | '/funnels'
    | '/media'
    | '/overview'
    | '/projects'
    | '/reports'
    | '/sessions'
    | '/settings'
    | '/sitemap'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_dash'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/_dash/api-keys'
    | '/_dash/documentation'
    | '/_dash/events'
    | '/_dash/funnels'
    | '/_dash/media'
    | '/_dash/overview'
    | '/_dash/projects'
    | '/_dash/reports'
    | '/_dash/sessions'
    | '/_dash/settings'
    | '/_dash/sitemap'
    | '/_dash/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/users': {
      id: '/_dash/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashUsersRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/sitemap': {
      id: '/_dash/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof DashSitemapRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/settings': {
      id: '/_dash/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashSettingsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/sessions': {
      id: '/_dash/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof DashSessionsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/reports': {
      id: '/_dash/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof DashReportsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/projects': {
      id: '/_dash/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof DashProjectsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/overview': {
      id: '/_dash/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof DashOverviewRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/media': {
      id: '/_dash/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof DashMediaRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/funnels': {
      id: '/_dash/funnels'
      path: '/funnels'
      fullPath: '/funnels'
      preLoaderRoute: typeof DashFunnelsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/events': {
      id: '/_dash/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof DashEventsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/documentation': {
      id: '/_dash/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DashDocumentationRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/api-keys': {
      id: '/_dash/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof DashApiKeysRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashApiKeysRoute: typeof DashApiKeysRoute
  DashDocumentationRoute: typeof DashDocumentationRoute
  DashEventsRoute: typeof DashEventsRoute
  DashFunnelsRoute: typeof DashFunnelsRoute
  DashMediaRoute: typeof DashMediaRoute
  DashOverviewRoute: typeof DashOverviewRoute
  DashProjectsRoute: typeof DashProjectsRoute
  DashReportsRoute: typeof DashReportsRoute
  DashSessionsRoute: typeof DashSessionsRoute
  DashSettingsRoute: typeof DashSettingsRoute
  DashSitemapRoute: typeof DashSitemapRoute
  DashUsersRoute: typeof DashUsersRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashApiKeysRoute: DashApiKeysRoute,
  DashDocumentationRoute: DashDocumentationRoute,
  DashEventsRoute: DashEventsRoute,
  DashFunnelsRoute: DashFunnelsRoute,
  DashMediaRoute: DashMediaRoute,
  DashOverviewRoute: DashOverviewRoute,
  DashProjectsRoute: DashProjectsRoute,
  DashReportsRoute: DashReportsRoute,
  DashSessionsRoute: DashSessionsRoute,
  DashSettingsRoute: DashSettingsRoute,
  DashSitemapRoute: DashSitemapRoute,
  DashUsersRoute: DashUsersRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
